### ISSUE TITLE
bad credentials when trying to use "github.mjs" to get a public repo info

### ISSUE THREAD

**Issue by shelper** [tanainc/tana-paste-examples#10]
e.g. i am trying to run:
` node github.mjs tiangolo typer` where the repo is a public one at https://github.com/tiangolo/typer
> /home/develop/oss/tana-paste-examples/node_modules/@octokit/request/dist-node/index.js:86
>       const error = new requestError.RequestError(toErrorMessage(data), status, {
>                     ^
> 
> RequestError [HttpError]: Bad credentials
>     at /home/develop/oss/tana-paste-examples/node_modules/@octokit/request/dist-node/index.js:86:21
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Job.doExecute (/home/develop/oss/tana-paste-examples/node_modules/bottleneck/light.js:405:18) {
>   status: 401,
>   response: {
>     url: 'https://api.github.com/repos/tiangolo/typer/pulls',
>     status: 401,
>     headers: {
>       'access-control-allow-origin': '*',
>       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
>       connection: 'close',
>       'content-length': '80',
>       'content-security-policy': "default-src 'none'",
>       'content-type': 'application/json; charset=utf-8',
>       date: 'Fri, 07 Jul 2023 21:12:34 GMT',
>       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
>       server: 'GitHub.com',
>       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
>       vary: 'Accept-Encoding, Accept, X-Requested-With',
>       'x-content-type-options': 'nosniff',
>       'x-frame-options': 'deny',
>       'x-github-media-type': 'github.v3; format=json',
>       'x-github-request-id': '63B8:08B8:1083A4:21638A:64A87FC2',
>       'x-ratelimit-limit': '60',
>       'x-ratelimit-remaining': '59',
>       'x-ratelimit-reset': '1688767954',
>       'x-ratelimit-resource': 'core',
>       'x-ratelimit-used': '1',
>       'x-xss-protection': '0'
>     },
>     data: {
>       message: 'Bad credentials',
>       documentation_url: 'https://docs.github.com/rest'
>     }
>   },
>   request: {
>     method: 'GET',
>     url: 'https://api.github.com/repos/tiangolo/typer/pulls',
>     headers: {
>       accept: 'application/vnd.github.v3+json',
>       'user-agent': 'octokit.js/1.8.1 octokit-core.js/3.6.0 Node.js/18.13.0 (linux; x64)',
>       authorization: 'token [REDACTED]'
>     },
>     request: { hook: [Function: bound bound register] }
>   }
> }
> 
> Node.js v18.13.0
>

**Comment by shelper** [comment]
nevermind, i think i need to put the token in config.mjs
